/**
 * WARNING: 禁止手工修改本文件
 * generated by doc2cpp at the Wed Mar 23 10:32:51 2016
 */
#include "xml2st/xml2st.h"

#ifndef	__t07001002_i_TBL_HEADER__
#define	__t07001002_i_TBL_HEADER__

typedef struct t07001002_i_body_s
{
    char * mid; // M [0-12] 会员编号
} t07001002_i_body_t;

typedef struct t07001002_i_root_s
{
    t07001002_i_body_t ** body; // O Single 体节点
} t07001002_i_root_t;

#ifdef	__cplusplus
extern	"C" {
#endif

const struct xml2st_table * ref_t07001002_i_root_tbl(void);

#ifdef	__cplusplus
}
#endif
#endif	/*__t07001002_i_TBL_HEADER__*/
