/**
 * WARNING: 禁止手工修改本文件
 * generated by doc2cpp at the Wed Mar 23 10:32:51 2016
 */
#include "./t07001002_i.h"
#include "xml2st/xml2st.h"

static const struct xml2st_column _body_columns_[] =
{
    DEF_X2S_MSTR("mid", 0,  t07001002_i_body_t, mid), // M [0-12] 会员编号
};

static const struct xml2st_table _body_table_ =
    DEF_X2S_MTBL("body", t07001002_i_body_t, _body_columns_);

static const struct xml2st_column _root_columns_[] =
{
    DEF_X2S_OPTR("body", t07001002_i_root_t, body, _body_table_), // O Single 体节点
};

static const struct xml2st_table _root_table_ =
    DEF_X2S_MTBL("root", t07001002_i_root_t, _root_columns_);

const struct xml2st_table * ref_t07001002_i_root_tbl(void)
{
    return &_root_table_;
}
