/**
 * WARNING: 禁止手工修改本文件
 * generated by doc2cpp at the Wed Mar 23 15:37:13 2016
 */
#include "xml2st/xml2st.h"

#ifndef	__t60006001_i_TBL_HEADER__
#define	__t60006001_i_TBL_HEADER__

typedef struct t60006001_i_body_s
{
    char * listedno; // O [0-20] 挂牌仓单编号
    char * mid; // O [12-12] 交易会员
    char * proposer; // O [4-4] 申请的操作员
    long * remark; // O 摘牌附言
    char * top; // O [2-2] 付款方式
} t60006001_i_body_t;

typedef struct t60006001_i_root_s
{
    t60006001_i_body_t ** body; // O Single 体节点
} t60006001_i_root_t;

#ifdef	__cplusplus
extern	"C" {
#endif

const struct xml2st_table * ref_t60006001_i_root_tbl(void);

#ifdef	__cplusplus
}
#endif
#endif	/*__t60006001_i_TBL_HEADER__*/
