/**
 * WARNING: 禁止手工修改本文件
 * generated by doc2cpp at the Wed Mar 23 15:37:13 2016
 */
#include "xml2st/xml2st.h"

#ifndef	__t60006001_o_TBL_HEADER__
#define	__t60006001_o_TBL_HEADER__

typedef struct t60006001_o_costpay_s
{
    char * costamt; // M [0-20] 费用金额
    char * costcode; // M [0-4] 费用代码
    long * flag; // M 费用标识
    char * trtype; // M [0-4] 交易类型
} t60006001_o_costpay_t;

typedef struct t60006001_o_body_s
{
    char * auditno; // M [0-128] 摘牌审核编号
    t60006001_o_costpay_t ** costpay; // O Single 费用列表
    char * delistno; // M [12-12] 摘牌编号
} t60006001_o_body_t;

typedef struct t60006001_o_root_s
{
    t60006001_o_body_t ** body; // O Single 体节点
} t60006001_o_root_t;

#ifdef	__cplusplus
extern	"C" {
#endif

const struct xml2st_table * ref_t60006001_o_root_tbl(void);

#ifdef	__cplusplus
}
#endif
#endif	/*__t60006001_o_TBL_HEADER__*/
