/**
 * WARNING: 禁止手工修改本文件
 * generated by doc2cpp at the Wed Mar 23 15:37:13 2016
 */
#include "./t60006001_o.h"
#include "xml2st/xml2st.h"

static const struct xml2st_column _costpay_columns_[] =
{
    DEF_X2S_MSTR("costamt", 0,  t60006001_o_costpay_t, costamt), // M [0-20] 费用金额
    DEF_X2S_MSTR("costcode", 0,  t60006001_o_costpay_t, costcode), // M [0-4] 费用代码
    DEF_X2S_MINT("flag", t60006001_o_costpay_t, flag), // M 费用标识
    DEF_X2S_MSTR("trtype", 0,  t60006001_o_costpay_t, trtype), // M [0-4] 交易类型
};

static const struct xml2st_table _costpay_table_ =
    DEF_X2S_MTBL("costpay", t60006001_o_costpay_t, _costpay_columns_);

static const struct xml2st_column _body_columns_[] =
{
    DEF_X2S_MSTR("auditno", 0,  t60006001_o_body_t, auditno), // M [0-128] 摘牌审核编号
    DEF_X2S_OPTR("costpay", t60006001_o_body_t, costpay, _costpay_table_), // O Single 费用列表
    DEF_X2S_MSTR("delistno", 0,  t60006001_o_body_t, delistno), // M [12-12] 摘牌编号
};

static const struct xml2st_table _body_table_ =
    DEF_X2S_MTBL("body", t60006001_o_body_t, _body_columns_);

static const struct xml2st_column _root_columns_[] =
{
    DEF_X2S_OPTR("body", t60006001_o_root_t, body, _body_table_), // O Single 体节点
};

static const struct xml2st_table _root_table_ =
    DEF_X2S_MTBL("root", t60006001_o_root_t, _root_columns_);

const struct xml2st_table * ref_t60006001_o_root_tbl(void)
{
    return &_root_table_;
}
