/**
 * WARNING: 禁止手工修改本文件
 * generated by doc2cpp at the Wed Mar 23 15:37:13 2016
 */
#include "./t60006001_i.h"
#include "xml2st/xml2st.h"

static const struct xml2st_column _body_columns_[] =
{
    DEF_X2S_OSTR("listedno", 0,  t60006001_i_body_t, listedno), // O [0-20] 挂牌仓单编号
    DEF_X2S_OSTR("mid", 0,  t60006001_i_body_t, mid), // O [12-12] 交易会员
    DEF_X2S_OSTR("proposer", 0,  t60006001_i_body_t, proposer), // O [4-4] 申请的操作员
    DEF_X2S_OINT("remark", t60006001_i_body_t, remark), // O 摘牌附言
    DEF_X2S_OSTR("top", 0,  t60006001_i_body_t, top), // O [2-2] 付款方式
};

static const struct xml2st_table _body_table_ =
    DEF_X2S_MTBL("body", t60006001_i_body_t, _body_columns_);

static const struct xml2st_column _root_columns_[] =
{
    DEF_X2S_OPTR("body", t60006001_i_root_t, body, _body_table_), // O Single 体节点
};

static const struct xml2st_table _root_table_ =
    DEF_X2S_MTBL("root", t60006001_i_root_t, _root_columns_);

const struct xml2st_table * ref_t60006001_i_root_tbl(void)
{
    return &_root_table_;
}
